version: '3'

services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
        working_dir: /code
        links:
            - redis:devcahce1
    php:
        build: ./php
        volumes:
            - ./code:/code
        working_dir: /code
        networks:
            - code-network
        links:
            - redis:devcahce1
            - db
            # :mysql
        # depends_on:
        #     - db


    redis:
        build: ./.docker/cache
        # deploy:
        #   resources:
        #     limits:
        #       cpus: '0.50'
        #       memory: 500M
        #     reservations:
        #        cpus: '0.25'
        #        memory: 200M
        #         michael@galliumos:~/Desktop/DockerizedElegantMVC$ free -m
        #               total        used        free      shared  buff/cache   available
        # Mem:           3900        1052         314         175        2533        2517
        # Swap:          5851           1        5849
        #
        #
        # doesn't seem to do much

        container_name: devcache1
        networks:
            - code-network

    db:
    #   image: mysql:5.7.22
    
      build: ./mysql
      restart: always
      container_name: mysql
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_USER: root
        MYSQL_DATABASE: emvc
      volumes:
        - dbdata:/var/lib/mysql
      networks:
        - code-network
        


networks:
    code-network:
        driver: bridge

volumes:
    dbdata:
