version: '3'

services:
    nginx: # todo get the nginx current version and modify the line with image: -->  build: ./services/nginx
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ./code:/code
            - ./services/nginx/conf/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
        working_dir: /code
        links:
            - redis:redisfrontend

    php:
        build: ./services/php
        # container_name: phpworker sincewe are scaling no need for this?
        volumes:
            - ./code:/code
        working_dir: /code
        networks:
            - code-network
        links:
            - redis:redisfrontend
            - mysql

    redis:
        build: ./services/redis
        container_name: redisfrontend
        networks:
            - code-network

    mysql:
      build: ./services/mysql
      restart: always
      container_name: mysql
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_USER: root
        MYSQL_DATABASE: emvc
      volumes:
        - mysqldata:/var/lib/mysql
      networks:
        - code-network   

networks:
    code-network:
        driver: bridge

volumes:
    mysqldata:
